version: "3.7"
services:
  rhasspy:
    container_name: rhasspy
    image: synesthesiam/rhasspy-server:latest
    volumes:
      - ${USERDIR}/rhasspy/profiles:/profiles
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "12101:12101"
    command: --profile en --user-profiles /profiles

  marytts:
    container_name: marytts
    image: synesthesiam/marytts:5.2
    restart: unless-stopped
    ports:
      - "59125:59125"

    #   nodered:
    #     container_name: node-red
    #     restart: always
    #     image: nodered/node-red-docker:latest
    #     depends_on:
    #       - "homeassistant"
    #     user: root
    #     volumes:
    #       - ${USERDIR}/node-red-1/user:/data
    #       - /etc/localtime:/etc/localtime:ro
    #     ports:
    #       - "1880:1880"

  homeassistant:
    container_name: home-assistant
    restart: always
    image: homeassistant/home-assistant:latest
    depends_on:
      - "influxdb"
      - "traefik"
    volumes:
      - ${USERDIR}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/home-assistant/media:/media
    #network_mode: host
    privileged: true
    # ports:
    #   - 8123:8123
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:ha.${DOMAINNAME}"
      - "traefik.port=8123"
      # - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.frontend.headers.contentSecurityPolicy=upgrade-insecure-requests"
      - "traefik.frontend.headers.customResponseHeaders=X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - com.centurylinklabs.watchtower.enable="false

  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto:latest
    volumes:
      - ${USERDIR}/mosquitto/config/:/mosquitto/config/
      - ${USERDIR}/mosquitto/log:/mosquitto/log
      - ${USERDIR}/mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    ports:
      - "1883:1883"
      - "9001:9001"
    #   - 8883:8883
    networks:
      - default
