version: '3'
services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    # links:
    #   - unbound
    ports:
      - "${LOCAL_IP}:53:53/tcp"
      - "${LOCAL_IP}:53:53/udp"
      # - "${LOCAL_IP}:80:80/tcp"
      - "${LOCAL_IP}:7443:443/tcp"
      - "${LOCAL_IP}:7080:80/tcp"
    cap_add:
      - NET_ADMIN
    depends_on:
      - traefik
      # - unbound
    environment:
      ServerIP: ${LOCAL_IP}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      VIRTUAL_PORT: 80
      # DNS1: 192.168.1.2#5322
      # DNS1: ${LOCAL_IP}#5322
      DNS1: 1.1.1.1
      DNS2: "no"
      IPv6: "no"
      TZ: ${TZ}
      # PROXY_LOCATION: pihole
    volumes:
      - ${USERDIR}/pihole:/etc/pihole
      # make sure to manually create this log file before first run
      - ${USERDIR}/pihole/log/pihole.log:/var/log/pihole.log
      - /etc/dnsmasq.d:/etc/dnsmasq.d
     # - ${USERDIR}/pihole/misc/dnsmasq.leases:/var/lib/misc/dnsmasq.leases
     # - ${USERDIR}/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # networks:
    #   pihole_unbound:
    #     ipv4_address: 192.168.1.3
    #   default:

  # unbound:
  #   container_name: unbound
  #   image: mvance/unbound
  #   depends_on:
  #     - pihole
  #   networks:
  #     pihole_unbound:
  #       ipv4_address: 192.168.1.2
  #   ports:
  #     - "9753:53/tcp"
  #     - "9753:53/udp"
  #     - "5333:5333/tcp"
  #     - "5333:5333/udp"
  #   # volumes:
  #     # - ${USERDIR}/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
  #     # - ${USERDIR}/unbound/root.hints:/var/unbound/etc/unbound/root.hints
  #     # - ${USERDIR}/unbound/unbound.log:/var/log/unbound/unbound.log
  #   cap_add:
  #   - NET_ADMIN
  #   restart: unless-stopped

  # unbound:
  #   image: folhabranca/unbound:latest
  #   #network_mode: bridge
  #   networks:
  #     pihole_unbound:
  #       ipv4_address: 192.168.1.2
  #     default:
  #   ports:
  #     - "5322:5322/udp"
  #     - "5322:5322"
  #   volumes:
  #     #- ${USERDIR}/unbound/unbound.conf.d:/opt/unbound/etc/unbound/unbound.conf.d
  #     - ${USERDIR}/unbound/unbound.log:/opt/unbound/etc/unbound/log/unbound.log
  #   environment:
  #     - INTERFACE=0.0.0.0
  #     - PORT=5322
  #     - DO_IPV6=no
  #     - DO_IPV4=yes
  #     - DO_UDP=yes
  #     - DO_TCP=yes
  #     - VERBOSITY=1
  #     - NUM_THREADS=1
  #     - SO_REUSEPORT=yes
  #     - HIDE_IDENTITY=yes
  #     - HIDE_VERSION=yes
  #     - QNAME_MINIMISATION=yes
  #     - RRSET_ROUNDROBIN=yes
  #     - USE_CAPS_FOR_ID=yes
  #     - ENABLE_REMOTE_CONTROL=yes
  #     - USE_LOGFILE=no
  #     - USE_CHROOT=yes
  #     - INFRA_HOST_TTL=60
  #   cap_add:
  #     - net_admin
  #   restart: always

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer:latest
    volumes:
      - ${USERDIR}/portainer:/data
      - ${USERDIR}/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"

  ipam:
    container_name: ipam
    depends_on:
      - mariadb
    image: pierrecdn/phpipam:latest
    volumes:
      - ${USERDIR}/phpipam:/var/www/
    environment:
      - MYSQL_ENV_MYSQL_USER=${MYSQL_ROOT_USER}
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ENV_MYSQL_HOST=mariadb
      - MYSQL_ENV_MYSQL_DB=${PHPIPAM_DATABASE}
    ports:
      - "3280:80"

  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower:latest
    depends_on:
      - "pihole"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    restart: always
    network_mode: "bridge"
    ports:
        - '8200:8200'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - ${USERDIR}/duplicati/config:/config
        - ${USERDIR}/duplicati/data:/data/Duplicati
        - ${BACKUP_DIR}/duplicatiBackups:/backups
        - ${USERDIR}:/source
        - /etc/localtime:/etc/localtime:ro

  netdata:
    image: titpetric/netdata
    container_name: netdata
    restart: always
    networks:
        - traefik_proxy
    ports:
        - 19999:19999
    volumes:
        - ${USERDIR}/netdata/proc:/host/proc:ro
        - ${USERDIR}/netdata/sys:/host/sys:ro
        - ${USERDIR}/netdata/var/run/docker.sock:/var/run/docker.sock:ro