resources:
  - url: /local/custom-lovelace/surveillance-card.js?v=0
    type: module
  - url: /local/custom-lovelace/weather-card/weather-card.js?v=0
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom-lovelace/calendar-card.js?v=1.3.1
    type: module

views:
  - title: main
    theme: night
    icon: mdi:home-outline
    cards:
    - type: glance
      title: Lights
      show_state: false
      entities:
        - entity: switch.office_lights
          name: Office
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: switch.dining_room_lights
          name: Dining Room
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: switch.living_room_lights
          name: Living Room
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: switch.kitchen_lights
          name: Kitchen
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: switch.bedroom_lights
          name: Bedroom
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: light.porch_light
          name: Front Porch
          icon: mdi:lamp
          tap_action:
            action: toggle
    - type: glance
      title: Doors
      show_state: false
      entities:
        - entity: binary_sensor.front_door_sensor_contact
          name: Front Door
          icon: mdi:door
        - entity: binary_sensor.kitchen_door_sensor_contact
          name: Kitchen Door
          icon: mdi:door
    - type: map
      default_zoom: 16
      dark_mode: true
      entities:
        - entity: !secret device_tracker_entity
        - zone.home
    - type: custom:weather-card
      entity: weather.dark_sky
      name: Weather
      icons: "/local/custom-lovelace/weather-card/icons/"
    - type: glance
      title: Things
      show_state: false
      entities:
        - entity: vacuum.roomba
          name: Roomba
          hold_action:
            action: more-info
          show_icon: true
          show_name: true
          tap_action:
            action: toggle
          type: entity-button
        - entity: switch.humidifier
          name: Humidifier
          show_icon: false
          show_name: true
          tap_action:
            action: toggle
            type: entity-button


  - title: temperature
    icon: mdi:thermometer-lines
    cards:
    - type: thermostat
      entity: climate.dining_room_nest
    - type: sensor
      entity: sensor.pi_one_temperature
      name: Bedroom Temperature
      graph: line
    - type: sensor
      entity: sensor.dark_sky_temperature
      name: Outside Temperature
      graph: line
    - type: sensor
      entity: sensor.front_door_sensor_temperature_measurement
      name: Front Door Temperature
      graph: line
    - type: sensor
      entity: sensor.kitchen_door_sensor_temperature_measurement
      name: Kitchen Door Temperature
      graph: line
    - type: sensor
      entity: sensor.office_motion_sensor_temperature_measurement
      name: Office Temperature
      graph: line
    - type: sensor
      entity: sensor.pi_one_humidity
      name: Bedroom Humidity
      graph: line
    - type: sensor
      entity: sensor.dining_room_thermostat_nest_humidity
      name: Dining Room Humidity
      graph: line

  - title: lights
    icon: mdi:desk-lamp
    cards:
    - type: glance
      show_state: false
      title: Bedroom
      entities:
        - entity: light.blaines_nightstand
          name: Blaine's Nightstand
          icon: mdi:desk-lamp
          tap_action:
            action: toggle
        - entity: light.beccas_nightstand
          name: Becca's Nightstand
          icon: mdi:desk-lamp
          tap_action:
            action: toggle
        - entity: switch.bedroom_grow_lights
          name: Plant Lights
          icon: mdi:lightbulb
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Kitchen
      entities:
        - entity: light.kitchen_sink
          name: Sink
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.kitchen_light_1
          name: Overhead 1
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.kitchen_light_2
          name: Overhead 2
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.kitchen_light_3
          name: Overhead 3
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.kitchen_light_4
          name: Overhead 4
          icon: mdi:lightbulb
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Dining Room
      entities:
        - entity: switch.dining_room_light
          name: Dining Room Floor Lamp
          icon: mdi:desk-lamp
          tap_action:
            action: toggle
        - entity: switch.window_lamp
          name: Window Light
          icon: mdi:desk-lamp
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Living Room
      entities:
        - entity: light.tv_light
          name: TV Lamp
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.couch_light
          name: Couch Lamp
          icon: mdi:lightbulb
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Office
      entities:
        - entity: light.office_1
          name: Overhead 1
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: light.office_2
          name: Overhead 2
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.office_floor_lamp
          name: Floor Lamp
          icon: mdi:lamp
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Outside
      entities:
        - entity: light.porch_light
          name: Front Porch
          icon: mdi:lightbulb
          tap_action:
            action: toggle
    - type: glance
      show_state: false
      title: Plants
      entities:
        - entity: switch.living_room_outlet
          name: Living Room Plants
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.kitchen_table_outlet
          name: Kitchen Plants
          icon: mdi:lightbulb
          tap_action:
            action: toggle

  - title: Cameras
    icon: mdi:cctv
    panel: true
    cards:
      # - type: custom:surveillance-card
      #   thumb_interval: 10
      #   update_interval: 2
      #   cameras:
      #       - entity: camera.livingroomcamerafront
      #       - entity: camera.livingroomcameraside
      - type: picture-entity
        entity: camera.livingroomcamera_front
  
  - title: Media
    icon: mdi:music-note
    cards:
    - type: media-control
      entity: media_player.living_room
    - type: media-control
      entity: media_player.spotify

  - title: Calendar
    icon: mdi:calendar
    cards:
    - type: "custom:calendar-card"
      showProgressBar: true
      numberOfDays: 7
      showColors: true
      todayColor: "green"
      textToday: "Today"
      linkColor: "white"
      entities:
        - !secret calendar_1
        - !secret calendar_2
        - !secret calendar_3
        - !secret calendar_4

  - title: TV & Movies
    icon: mdi:television-box
